spring:
  data:
    mongodb:
      username: skyscanner_dbowner
      password: password123
      authentication-database: skyscanner
      database: skyscanner
      uri: mongodb://skyscanner_dbowner:password123@192.168.56.7:27017/skyscanner
  graphql:
    graphiql:
      enabled: true